// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PackSizesRepository is an autogenerated mock type for the PackSizesRepository type
type PackSizesRepository struct {
	mock.Mock
}

// AddPackSize provides a mock function with given fields: size
func (_m *PackSizesRepository) AddPackSize(size int) {
	_m.Called(size)
}

// GetPackSizes provides a mock function with given fields:
func (_m *PackSizesRepository) GetPackSizes() []int {
	ret := _m.Called()

	var r0 []int
	if rf, ok := ret.Get(0).(func() []int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// RemovePackSize provides a mock function with given fields: size
func (_m *PackSizesRepository) RemovePackSize(size int) {
	_m.Called(size)
}

// NewPackSizesRepository creates a new instance of PackSizesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackSizesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PackSizesRepository {
	mock := &PackSizesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
